sudo: false

language: java

jdk:
  - oraclejdk8

# https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-130860338
addons:
  apt:
    packages:
      - oracle-java8-installer

env:
	global:
		- spring.profiles.active=h2

# https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
script: travis_wait 360 mvn -B test -U -e
